Gemfile, Gemfile.lock, app/models/card.rb, app/models/product.rb, config/environments/development.rb, config/storage.yml, db/migrate/20231128103958_create_active_storage_tables.active_storage.rb, db/schema.rb
add active storage and cloudinary
=> add active storage and cloudinary

app/assets/stylesheets/pages/_home.scss, app/views/pages/home.html.erb
Added home page that may be used as a root page
=> Home page setup 2811

Gemfile, Gemfile.lock, app/controllers/cards_controller.rb, app/views/cards/index.html.erb, config/initializers/openai.rb
- Added Chatgpt configuration that works (code to launch it in cards controller/view index to move in the chats)
- Fixed PG Search
=> added chatgpt config and fixed the pg search

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_search_bar.scss, app/assets/stylesheets/config/_fonts.scss, app/views/cards/index.html.erb, app/views/layouts/application.html.erb
=> Modify index cards 2811

app/controllers/cards_controller.rb, app/models/card.rb, app/models/category.rb
=> Fixed the pg search

Gemfile.lock, app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_modal_card.scss, app/assets/stylesheets/components/_search_bar.scss, app/assets/stylesheets/config/_custom_variables.scss, app/assets/stylesheets/config/_fonts.scss, app/javascript/controllers/controller_scroll_cards_controller.js, app/javascript/controllers/scroll_cards_controller.js, app/views/cards/index.html.erb, app/views/layouts/application.html.erb, app/views/shared/_modal_cards.html.erb
Added card with design and so on
=> Js card scroll 2811

app/assets/stylesheets/components/_search_bar.scss, app/views/cards/index.html.erb
add a shadow + fix the size and form of the search bar
=> fix search bar in the index for cards

app/controllers/application_controller.rb, app/views/cards/admin_cards.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, config/initializers/devise.rb, config/initializers/rails_admin.rb
card category product user only in admin dashboard
=> Devise 2911

app/controllers/chatrooms_controller.rb, app/controllers/messages_controller.rb, app/views/chatrooms/show.html.erb, config/routes.rb, db/migrate/20231130150201_add_on_off_gpt_to_chatrooms.rb, db/schema.rb
=> chat gpt turn off

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/components/_search_bar.scss, app/views/cards/index.html.erb
=> Modify card 0112

app/assets/stylesheets/components/_navbar.scss
modify style of the search bar
=> modify style of the search bar

app/views/chatrooms/show.html.erb
=> removing remote true

app/views/shared/_logo_menu.erb, app/views/shared/_navbar_mobile.html.erb
=> Change search bar icons 0112

app/assets/stylesheets/components/_navbar.scss
=> remove bordr radius

app/views/shared/_navbar_mobile.html.erb
add redirection de merde de nico
=> add redirection de merde de nico

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_modal_card.scss, app/assets/stylesheets/components/_search_bar.scss, app/views/cards/index.html.erb, app/views/shared/_modal_cards.html.erb, app/views/shared/_navbar_mobile.html.erb, db/seeds.rb
modify the front of the card page
=> modify the front of the card page

db/schema.rb, db/seeds.rb
modify seeds adding picture for each topic
=> modify seeds

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_search_bar.scss, app/views/cards/index.html.erb
category links
color by category
background cards
border, etc.
=> Category color

app/assets/stylesheets/components/_index.scss, app/javascript/controllers/switch_to_a_pro_controller.js, app/views/chatrooms/show.html.erb, app/views/pages/home.html.erb, app/views/shared/_chat_card.html.erb, app/views/shared/_chat_marketplace.html.erb, app/views/shared/_flashes.html.erb
=> Home page first try 0512

app/assets/stylesheets/components/_navbar.scss, app/views/shared/_navbar_mobile.html.erb
=> fix third emoji

app/assets/stylesheets/components/_navbar.scss, app/views/shared/_navbar_mobile.html.erb
=> modify navbar border

app/assets/stylesheets/components/_product_card.scss, app/views/messages/_marketplace_message.html.erb, app/views/messages/_marketplace_message_main.html.erb, app/views/shared/_modal_product.html.erb, db/seeds.rb
=> product card + carrousel

app/javascript/controllers/chatroom_subscription_controller.js, app/javascript/controllers/loader_controller.js, app/javascript/controllers/switch_to_a_pro_controller.js, app/views/messages/_message.html.erb, app/views/shared/_chat_card.html.erb, app/views/shared/_chat_marketplace.html.erb
=> Loader Otisbot

app/assets/stylesheets/components/_product_carrousel.scss
modify margin product carroussel margin
=> modify margin product carroussel margin

app/javascript/controllers/home_controller.js
=> fix animation

app/views/messages/_message.html.erb
modify display for the professional
=> modify display for the professional

app/assets/stylesheets/components/_modal_card.scss, app/views/messages/_marketplace_message_main.html.erb, app/views/shared/_modal_cards.html.erb
=> Modify title product 0712
